# Generated by Django 4.2 on 2023-04-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='holat',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
