# Generated by Django 4.2 on 2023-04-17 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyurtma', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buyurtma',
        ),
        migrations.AddField(
            model_name='savatitem',
            name='yetkazish_puli',
            field=models.PositiveSmallIntegerField(default=15000),
        ),
        migrations.AlterField(
            model_name='savatitem',
            name='savat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemlari', to='buyurtma.savat'),
        ),
    ]
