# Generated by Django 4.2 on 2023-04-17 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
        ('buyurtma', '0002_delete_buyurtma_savatitem_yetkazish_puli_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyurtma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holat', models.CharField(blank=True, max_length=30)),
                ('sana', models.DateField(auto_now_add=True)),
                ('profil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.profil')),
                ('savat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyurtma.savat')),
            ],
        ),
    ]
