# Generated by Django 4.2 on 2023-04-17 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyurtma', '0003_buyurtma'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buyurtma',
        ),
    ]
